version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "15672:15672" # Management UI
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - eatup_backend
    restart: unless-stopped

  seq:
    image: datalust/seq:latest
    container_name: seq
    ports:
      - "5341:80" # HTTP UI and ingestion endpoint
      - "5342:5342" # Optional ingestion over secure channel (if enabled)
    environment:
      - ACCEPT_EULA=Y
    networks:
      - eatup_backend
    volumes:
      - seq_data:/data

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      ACCEPT_EULA: ${ACCEPT_EULA}
      SA_PASSWORD: ${SA_PASSWORD}
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - eatup_backend
    restart: unless-stopped

  eatup-spa:
    image: ghcr.io/mma-development/eatup-spa:${SPA_IMAGE_TAG}
    ports:
      - "80:80"
    environment:
      MY_APP_ENCRYPT_KEY: ${MY_APP_ENCRYPT_KEY}
      MY_APP_API_BASE_URL: ${MY_APP_API_BASE_URL}
  eatup-files:
    image: ghcr.io/mma-development/eatup-files:${FILES_IMAGE_TAG}
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Server=mssql;Database=EatUpFiles;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;"
      RabbitMQ__Host: ${RabbitMQ__Host}
      RabbitMQ__Exchange: ${RabbitMQ__Exchange}
      RabbitMQ__Queue: "files"
      RabbitMQ__Username: ${RabbitMQ__Username}
      RabbitMQ__Password: ${RabbitMQ__Password}
      Azure__ConnectionString: ${Azure__ConnectionString}
    networks:
      - eatup_backend
    depends_on:
      - mssql
      - rabbitmq
    restart: unless-stopped
  eatup-hangfire:
    image: ghcr.io/mma-development/eatup-hangfire:${HANGFIRE_IMAGE_TAG}
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__HangfireConnection: "Server=mssql;Database=EatUpHangfire;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;"
      RabbitMQ__Host: ${RabbitMQ__Host}
      RabbitMQ__Exchange: ${RabbitMQ__Exchange}
      RabbitMQ__Queue: "hangfire"
      RabbitMQ__Username: ${RabbitMQ__Username}
      RabbitMQ__Password: ${RabbitMQ__Password}
      Hangfire__Username: ${Hangfire__Username}
      Hangfire__Password: ${Hangfire__Password}
    networks:
      - eatup_backend
    depends_on:
      - mssql
      - rabbitmq
    ports:
      - "8081:8080"
    restart: unless-stopped

  eatup-users:
    image: ghcr.io/mma-development/eatup-users:${USERS_IMAGE_TAG}
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Server=mssql;Database=EatUpUsers;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;"
      VendorJwt__Secret: ${VENDOR_JWT_SECRET}
      VendorJwt__Issuer: ${VENDOR_JWT_ISSUER}
      VendorJwt__Audience: ${VENDOR_JWT_AUDIENCE}
      UserJwt__Secret: ${USER_JWT_SECRET}
      UserJwt__Issuer: ${USER_JWT_ISSUER}
      UserJwt__Audience: ${USER_JWT_AUDIENCE}
      StripeSettings__Secret: ${STRIPE_SECRET}
      RabbitMQ__Host: ${RabbitMQ__Host}
      RabbitMQ__Exchange: ${RabbitMQ__Exchange}
      RabbitMQ__Queue: "users"
      RabbitMQ__Username: ${RabbitMQ__Username}
      RabbitMQ__Password: ${RabbitMQ__Password}
    networks:
      - eatup_backend
    depends_on:
      - mssql
      - rabbitmq
    restart: unless-stopped

  eatup-vendors:
    image: ghcr.io/mma-development/eatup-vendors:${VENDORS_IMAGE_TAG}
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Server=mssql;Database=EatUpVendors;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;"
      VendorJwt__Secret: ${VENDOR_JWT_SECRET}
      VendorJwt__Issuer: ${VENDOR_JWT_ISSUER}
      VendorJwt__Audience: ${VENDOR_JWT_AUDIENCE}
      UserJwt__Secret: ${USER_JWT_SECRET}
      UserJwt__Issuer: ${USER_JWT_ISSUER}
      UserJwt__Audience: ${USER_JWT_AUDIENCE}
      StripeSettings__Secret: ${STRIPE_SECRET}
      StripeSettings__ReturnUrl: "http://example.com"
      StripeSettings__ReAuth: "http://example.com"
      RabbitMQ__Host: ${RabbitMQ__Host}
      RabbitMQ__Exchange: ${RabbitMQ__Exchange}
      RabbitMQ__Queue: "vendors"
      RabbitMQ__Username: ${RabbitMQ__Username}
      RabbitMQ__Password: ${RabbitMQ__Password}
    networks:
      - eatup_backend
    depends_on:
      - mssql
      - rabbitmq
    restart: unless-stopped

  eatup-orders:
    image: ghcr.io/mma-development/eatup-orders:${ORDERS_IMAGE_TAG}
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Server=mssql;Database=EatUpOrders;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;"
      VendorJwt__Secret: ${VENDOR_JWT_SECRET}
      VendorJwt__Issuer: ${VENDOR_JWT_ISSUER}
      VendorJwt__Audience: ${VENDOR_JWT_AUDIENCE}
      UserJwt__Secret: ${USER_JWT_SECRET}
      UserJwt__Issuer: ${USER_JWT_ISSUER}
      UserJwt__Audience: ${USER_JWT_AUDIENCE}
      StripeSettings__Secret: ${STRIPE_SECRET}
      RabbitMQ__Host: ${RabbitMQ__Host}
      RabbitMQ__Exchange: ${RabbitMQ__Exchange}
      RabbitMQ__Queue: "orders"
      RabbitMQ__Username: ${RabbitMQ__Username}
      RabbitMQ__Password: ${RabbitMQ__Password}
    networks:
      - eatup_backend
    depends_on:
      - mssql
      - rabbitmq
    restart: unless-stopped

  eatup-meals:
    image: ghcr.io/mma-development/eatup-meals:${MEALS_IMAGE_TAG}
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Server=mssql;Database=EatUpMeals;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;"
      VendorJwt__Secret: ${VENDOR_JWT_SECRET}
      VendorJwt__Issuer: ${VENDOR_JWT_ISSUER}
      VendorJwt__Audience: ${VENDOR_JWT_AUDIENCE}
      UserJwt__Secret: ${USER_JWT_SECRET}
      UserJwt__Issuer: ${USER_JWT_ISSUER}
      UserJwt__Audience: ${USER_JWT_AUDIENCE}
      StripeSettings__Secret: ${STRIPE_SECRET}
      RabbitMQ__Host: ${RabbitMQ__Host}
      RabbitMQ__Exchange: ${RabbitMQ__Exchange}
      RabbitMQ__Queue: "meals"
      RabbitMQ__Username: ${RabbitMQ__Username}
      RabbitMQ__Password: ${RabbitMQ__Password}
    networks:
      - eatup_backend
    depends_on:
      - mssql
      - rabbitmq
    restart: unless-stopped

  eatup-gateway:
    image: ghcr.io/mma-development/eatup-gateway:${GATEWAY_IMAGE_TAG}
    environment:
      Seq__ServerUrl: ${Seq__Host}
      Seq__ApiKey: ${Seq__ApiKey}
      ASPNETCORE_ENVIRONMENT: "Development"
      ReverseProxy__Clusters__users__Destinations__destination1__Address: ${ReverseProxy__Clusters__users__Destinations__destination1__Address}
      ReverseProxy__Clusters__vendors__Destinations__destination1__Address: ${ReverseProxy__Clusters__vendors__Destinations__destination1__Address}
      ReverseProxy__Clusters__orders__Destinations__destination1__Address: ${ReverseProxy__Clusters__orders__Destinations__destination1__Address}
      ReverseProxy__Clusters__meals__Destinations__destination1__Address: ${ReverseProxy__Clusters__meals__Destinations__destination1__Address}
      ReverseProxy__Clusters__files__Destinations__destination1__Address: ${ReverseProxy__Clusters__files__Destinations__destination1__Address}
    ports:
      - "8080:8080"
    networks:
      - eatup_backend
    depends_on:
      - eatup-users
      - eatup-vendors
      - eatup-orders
      - eatup-meals
    restart: unless-stopped

volumes:
  rabbitmq_data:
  mssql_data:
  seq_data:


networks:
  eatup_backend:
    driver: bridge
