version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # RabbitMQ default protocol port
      - "15672:15672"  # RabbitMQ Management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    ports:
      - "1433:1433"  # MSSQL default port
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Password"
    volumes:
      - mssql_data:/var/opt/mssql
    restart: unless-stopped
  
volumes:
  rabbitmq_data:

networks:
    default:
        driver: bridge
        name: eatup_network
    
    mssql_data:
        driver: local
        name: mssql_data
 