name: Deploy Gateway to Azure Container Apps

on:
  push:
    branches:
      - master
    paths:
      - 'EatUp.Gateway/**'

  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker image to GHCR
      run: |
        IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/eatup-gateway:latest
        docker build -f EatUp.Gateway/Dockerfile -t $IMAGE_NAME .
        docker push $IMAGE_NAME

    # - name: Log in to Azure
    #   uses: azure/login@v1
    #   with:
    #     creds: ${{ secrets.AZURE_CREDENTIALS }}

    # - name: Deploy to Azure Container Apps
    #   uses: azure/container-apps-deploy-action@v1
    #   with:
    #     resourceGroup: my-resource-group
    #     containerAppName: my-container-app
    #     containerAppEnvironment: my-container-app-environment
    #     imageToDeploy: ghcr.io/${{ github.repository_owner }}/myapp:latest
    #     registryUrl: ghcr.io
    #     registryUsername: ${{ github.actor }}
    #     registryPassword: ${{ secrets.GITHUB_TOKEN }}
    #     environmentVariables: |
    #       ${{
    #         format('APP_SETTINGS={0}', secrets.APP_SETTINGS)
    #       }}
