name: Deploy Users to Azure Container Apps

on:
  push:
    branches:
      - master
    paths:
      - 'EatUp.Users/**'

  workflow_dispatch:

jobs:
  build:
    permissions: write-all

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker image to GHCR
      run: |
        IMAGE_NAME=ghcr.io/mma-development/eatup-users:latest
        docker build -f EatUp.Users/Dockerfile -t $IMAGE_NAME .
        docker push $IMAGE_NAME

  deploy:
    environment: Production
    runs-on: ubuntu-latest
    
    needs: [build]
    steps:
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Container Apps
      uses: azure/container-apps-deploy-action@v1
      with:
        resourceGroup: EatUp
        containerAppName: eatup-users
        containerAppEnvironment: EatUp
        imageToDeploy: ghcr.io/mma-development/eatup-users:latest
        registryUrl: ghcr.io
        registryUsername: ${{ secrets.GHCR_USERNAME }}
        registryPassword: ${{ secrets.GHCR_PAT }}
